version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.1.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: gem install bundler:1.17.2
      - run:
          name: install missing gems for fastlane 
          command: bundle install
      - run:
          name: build and test run 
          command: fastlane scan
          environment: 
           SCAN_DEVICE: iphone 8
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
          
workflows:
  build-and-test:
    jobs:
      - build-and-test
